-- This is Users Table
CREATE TABLE Users (
    userId CHAR(36) PRIMARY KEY COMMENT 'UUID that will be generated by application',
    fullName VARCHAR(100) NOT NULL COMMENT 'User full name',
    phoneNumber VARCHAR(20) COMMENT 'Customer phone number starting with(+250)',
    userType ENUM('PERSON','BUSINESS','SYSTEM') COMMENT 'categorizing customer for business purpose'
);

-- This is Category Groups Table
CREATE TABLE CategoryGroups (
    groupId CHAR(36) PRIMARY KEY COMMENT 'Unique ID for the table',
    groupName ENUM('UTILITY','PAYMENT','AIRTIME','DATA','TRANSFER') COMMENT 'Grouping should contain the listed services(functionalities'
);

-- This is Transaction Categories Table
CREATE TABLE TransactionCategories (
    categoryId CHAR(36) PRIMARY KEY,
    categoryName VARCHAR(50) COMMENT 'Name of category. For example, water service',
    content TEXT COMMENT 'JSON metadata to describe category rules',
    groupId CHAR(36),
    FOREIGN KEY (groupId) REFERENCES CategoryGroups(groupId)
);

-- This is System Logs Table
CREATE TABLE SystemLogs (
    logId CHAR(36) PRIMARY KEY,
    smsAddress VARCHAR(50) COMMENT 'Identifies sender, for example, MoMopay',
    messageBody TEXT COMMENT 'This is the main message(content of SMS)',
    receivedAt DATETIME COMMENT 'The date sms was received at',
    processedAt DATETIME COMMENT 'Time parsing of sms data was completed',
    status VARCHAR(20) COMMENT 'Status can either be processed, pending, error'
);

-- This is Services Table
CREATE TABLE Services (
    serviceId CHAR(36) PRIMARY KEY,
    serviceName VARCHAR(100) COMMENT 'Name of service',
    serviceType ENUM('UTILITY','AIRTIME','DATA','MERCHANT'),
    providerPhone VARCHAR(20) COMMENT 'Phone number required for the service provider'
);

-- This is Transactions Table
CREATE TABLE Transactions (
    transactionId CHAR(36) PRIMARY KEY,
    externalTransactionId VARCHAR(50) UNIQUE NOT NULL COMMENT 'Transaction ID from the telecom provider',
    amount DECIMAL(10,2) NOT NULL COMMENT 'This is the value of transaction happened and it is positive',
    currency VARCHAR(5) DEFAULT 'RWF' COMMENT 'This is the currency. We set the default to Rwanda franc',
    transactionDate DATETIME NOT NULL COMMENT 'The date transaction happened',
    transactionType ENUM('INCOMING','OUTGOING') COMMENT 'Transaction can be either of these',
    fee DECIMAL(10,2),
    balanceAfter DECIMAL(10,2) NOT NULL COMMENT 'Remaining balance after transaction',
    categoryId CHAR(36),
    serviceId CHAR(36),
    logId CHAR(36) COMMENT 'References source sms',
    FOREIGN KEY (categoryId) REFERENCES TransactionCategories(categoryId),
    FOREIGN KEY (serviceId) REFERENCES Services(serviceId),
    FOREIGN KEY (logId) REFERENCES SystemLogs(logId)
);

-- This is Transaction Users Table
CREATE TABLE TransactionUsers (
    transactionId CHAR(36),
    userId CHAR(36),
    role ENUM('SENDER','RECEIVER') COMMENT 'User can be sender or receiver',
    PRIMARY KEY (transactionId, userId, role),
    FOREIGN KEY (transactionId) REFERENCES Transactions(transactionId),
    FOREIGN KEY (userId) REFERENCES Users(userId)
);


--Money must be positive
ALTER TABLE Transactions
ADD CONSTRAINT amount_should_be_positive CHECK (amount >= 0);
-- Balance cannot be negative
ALTER TABLE Transactions
ADD CONSTRAINT balance_should_be_positive CHECK (balanceAfter >= 0);

--to make sure logs only use valid statuses
ALTER TABLE SystemLogs
ADD CONSTRAINT logs_status CHECK (status IN ('PENDING', 'PROCESSED', 'ERROR'));
